"""add_is_archived_and_science_tables

Revision ID: 046aa15cefd0
Revises: 45142dd5ccd9
Create Date: 2026-02-13 17:54:56.612284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046aa15cefd0'
down_revision: Union[str, Sequence[str], None] = '45142dd5ccd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
