"""add_hr_fields

Revision ID: 06ce3c23fe54
Revises: 046aa15cefd0
Create Date: 2026-02-20 17:26:20.934995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ce3c23fe54'
down_revision: Union[str, Sequence[str], None] = '046aa15cefd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('admission_date', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('termination_date', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'birth_date')
    op.drop_column('employees', 'termination_date')
    op.drop_column('employees', 'admission_date')
    # ### end Alembic commands ###
