"""add science and archive to mural

Revision ID: 45142dd5ccd9
Revises: e59052ffbd14
Create Date: 2026-02-13 17:43:58.697928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45142dd5ccd9'
down_revision: Union[str, Sequence[str], None] = 'e59052ffbd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'is_archived')
    # ### end Alembic commands ###
