"""add attachments to announcements

Revision ID: e59052ffbd14
Revises: eea49013e495
Create Date: 2026-02-13 17:31:51.541127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59052ffbd14'
down_revision: Union[str, Sequence[str], None] = 'eea49013e495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('attachment_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'attachment_name')
    op.drop_column('announcements', 'attachment_url')
    # ### end Alembic commands ###
